# Generated by Django 4.0.4 on 2022-05-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school2',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
