# Generated by Django 4.0.4 on 2022-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_school2_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addaschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=80)),
                ('postelcode', models.CharField(max_length=8)),
                ('addressone', models.CharField(max_length=100)),
                ('addresstwo', models.CharField(max_length=100)),
                ('googlemaplink', models.CharField(max_length=100)),
                ('trainstation', models.CharField(max_length=100)),
                ('busstation', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=30)),
                ('ownerphone', models.CharField(max_length=15)),
                ('personincharge', models.CharField(max_length=30)),
                ('picphone', models.CharField(max_length=15)),
            ],
        ),
    ]
