# Generated by Django 4.0.4 on 2022-06-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_addaschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school2',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
