# Generated by Django 4.0.4 on 2022-06-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_school2_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaschool',
            name='schoolfax',
            field=models.CharField(default=20, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addaschool',
            name='schoolname',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addaschool',
            name='schoolphone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
